export const starter = {
  categories: [
    {
      categoryName: 'The Desert',
      categoryId: 'thedesert',
      categoryDescription:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus nostrum laborum adipisci alias fuga culpa.',
      categoryCover: 'DesertCover',
      width: '451',
      height: '438',
      photos: [
        {
          photoId: 'desert-1',
          photoTitle: 'Desert 1',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '867',
          height: '578',
        },
        {
          photoId: 'desert-2',
          photoTitle: 'Desert 2',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '867',
          height: '578',
        },
        {
          photoId: 'desert-3',
          photoTitle: 'Desert 3',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '867',
          height: '487',
        },
        {
          photoId: 'desert-4',
          photoTitle: 'Desert 4',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '867',
          height: '578',
        },
        {
          photoId: 'desert-5',
          photoTitle: 'Desert 5',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '646',
          height: '646',
        },
        {
          photoId: 'desert-6',
          photoTitle: 'Desert 6',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '663',
          height: '646',
        },
      ],
    },
    {
      categoryName: 'High Sierra',
      categoryId: 'highsierra',
      categoryDescription:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus nostrum laborum adipisci alias fuga culpa.',
      categoryCover: 'SierraCover',
      width: '450',
      height: '610',
      photos: [
        {
          photoId: 'sierra-1',
          photoTitle: 'High Sierra 1',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '516',
          height: '646',
        },
        {
          photoId: 'sierra-2',
          photoTitle: 'High Sierra 2',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '638',
        },
        {
          photoId: 'sierra-3',
          photoTitle: 'High Sierra 3',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '927',
          height: '584',
        },
        {
          photoId: 'sierra-4',
          photoTitle: 'High Sierra 4',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'sierra-5',
          photoTitle: 'High Sierra 5',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'sierra-6',
          photoTitle: 'High Sierra 6',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'sierra-7',
          photoTitle: 'High Sierra 7',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'sierra-8',
          photoTitle: 'High Sierra 8',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
      ],
    },
    {
      categoryName: 'Beach',
      categoryId: 'beach',
      categoryDescription:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus nostrum laborum adipisci alias fuga culpa.',
      categoryCover: 'BeachCover',
      width: '502',
      height: '584',
      photos: [
        {
          photoId: 'beach-1',
          photoTitle: 'Beach 1',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '734',
          height: '646',
        },
        {
          photoId: 'beach-2',
          photoTitle: 'Beach 2',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '861',
          height: '646',
        },
        {
          photoId: 'beach-3',
          photoTitle: 'Beach 3',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'beach-4',
          photoTitle: 'Beach 4',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'beach-5',
          photoTitle: 'Beach 5',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '466',
          height: '646',
        },
        {
          photoId: 'beach-6',
          photoTitle: 'Beach 6',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
      ],
    },
    {
      categoryName: 'Forests Wilderness',
      categoryId: 'forestswilderness',
      categoryDescription:
        'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus nostrum laborum adipisci alias fuga culpa.',
      categoryCover: 'ForestCover',
      width: '409',
      height: '437',
      photos: [
        {
          photoId: 'forest-1',
          photoTitle: 'Forest 1',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '653',
        },
        {
          photoId: 'forest-2',
          photoTitle: 'Forest 2',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'forest-3',
          photoTitle: 'Forest 3',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '591',
          height: '646',
        },
        {
          photoId: 'forest-4',
          photoTitle: 'Forest 4',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'forest-5',
          photoTitle: 'Forest 5',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'forest-6',
          photoTitle: 'Forest 6',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'forest-7',
          photoTitle: 'Forest 7',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
        {
          photoId: 'forest-8',
          photoTitle: 'Forest 8',
          photoDescription: 'Photo Description Placeholder',
          liked: false,
          width: '928',
          height: '618',
        },
      ],
    },
  ],
};
